version: 0.0.{build}
os: Visual Studio 2015
clone_folder: c:\projects\takoyaki
environment:
  BOOST_ROOT: c:\projects\takoyaki\boost_1_59_0
platform:
  - x64

configuration:
  - Debug
  
before_build:
- ps: $ ./boost.ps1
- ps: dir